#lang sicp
(define call-the-cops  (lambda ()
    (display "WIUWIUWIU... Police chase activated!!!")))

(define (make-account balance password)
    (define counter 0)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin  (set! balance (- balance amount))
                    balance)
            "Insufficient funds"))
    (define (deposit amount)
        (set! balance (+ balance amount))
        balance)
    (define (nothing val)
        (display "Incorrect password!"))
    (define (dispatch pass m)  
        (cond   ((and (eq? pass password) (eq? m 'withdraw)) 
                    (set! counter 0)
                    withdraw)
                ((and (eq? pass password) (eq? m 'deposit))
                    (set! counter 0)
                    deposit)
                ((not (eq? pass password))  (cond   ((>= counter 7) (call-the-cops))
                                                    (else ( (set! counter (+ counter 1))
                                                            nothing) )))
                (else (error "Unknown request: MAKE-ACCOUNT ")
                        nothing)))
    dispatch)

(define acc (make-account 100 'qwerty))
((acc 'qwert 'withdraw) 3)
